### ISSUE TITLE
Widget will not run when optimization fails

### ISSUE THREAD

**Issue by bnomei** [fabianmichael/kirby-imagekit#10]
i got imagekit and imageset installed. page loads and images are created on the fly but widget fails – stuck start of at creating images.

`TypeError: undefined is not an object (evaluating 'e.message')` somewhere near

```js
v.index(function(e){w.value(e.current/e.total).text(i("imagekit.widget.progress.scanning")+" "+e.current+"/"+e.total)
```

**Comment by fabianmichael** [comment]
This is probably caused by an invalid (non-JSON) request returned by the server. Please help me with finding the issue by following the steps described below:

1. Open you browser’s developer tools (before starting the widget) and have a look at the network tab and especially at the XHR requests.
2. Start the thumbnail generation process and see, after which request the widget fails.
3. Post a screenshot of the failed request to this issue, including request/response headers, request url and response text.

After that, I can have a look what went wrong ;-)

**Comment by bnomei** [comment]
panel session terminated during lunchbreak so i had to log in again. now the widget does not fail at checking the pages ('durchsuche'). now it finds them but does not proceed creating thumbs ('Erstelle thumbnails …') – same js error as mentioned above.
i have an error and sitemap plugin installed as well. i have a one-pager setup where childs redirect to parent url with hash (disabled that for now).

thx for responding so quickly.

XHR 'create':

```
{"status":"success","code":200,"message":true,"data":{"pending":2585,"created":184}}<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /MYPATH/index.php:16) in <b>/MYPATH/kirby/vendor/getkirby/toolkit/lib/response.php</b> on line <b>64</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /MYPATH/index.php:16) in <b>/MYPATH/kirby/vendor/getkirby/toolkit/lib/response.php</b> on line <b>65</b><br />
{"status":"error","code":0,"message":"An unexpected error occurred! Enable debug mode for more info: https:\/\/getkirby.com\/docs\/cheatsheet\/options\/debug"}
```

**Comment by bnomei** [comment]
line 16 in index.php is `echo $kirby->launch();`

**Comment by bnomei** [comment]
it seems i also had the PATHs for the optimizers wrong. imagekit could warn about that.
now i get a different error when `creating`.

```
{"status":"error","code":2,"message":"filesize(): stat failed for 
\/MYPATH\/thumbs\MYPATH\/SOMEFILE-0354-320x213-58beccefb4e2f.jpg in file: 
\/MYPATH\/kirby\/vendor\/getkirby\/toolkit\/lib\/f.php on line: 476"}
{"status":"error","code":2,"message":"Cannot modify header information - headers already sent by
 (output started at \/MYPATH\/kirby\/vendor\/filp\/whoops\/src\/Whoops\/Run.php:398) in file: 
\/MYPATH\/site\/plugins\/imagekit\/lib\/complainingthumb.php on line: 152"}
```

**Comment by fabianmichael** [comment]
Great idea! I’m leaving this issue open as a reminder. Will think about how to implement error messages with the option to continue when optimization fails.

**Comment by bnomei** [comment]
ok but even without optimization i still get the error when creating.

**Comment by bnomei** [comment]
- it has about 2000 thumbs in queue. 
- the server has about 30sec php script time available. 
- memory limit is at least 100M
- imageset defines `320-1920,1` so 320px, 1120px and 1920px thumbs are issued

1) without optimisation it seems to create 5 – always 5 and then fail.

```
{"status":"success","code":200,"message":true,"data":{"pending":2493,"created":276}}<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /PATH/index.php:16) in <b>/PATH/kirby/vendor/getkirby/toolkit/lib/response.php</b> on line <b>64</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /PATH/index.php:16) in <b>/PATH/kirby/vendor/getkirby/toolkit/lib/response.php</b> on line <b>65</b><br />
{"status":"error","code":2,"message":"Cannot modify header information - headers already sent by (output started at \/PATH\/index.php:16) in file: \/PATH\/site\/plugins\/imagekit\/lib\/complainingthumb.php on line: 152"}
```

2) with debug and with optimisation enabled only one file get created.

```
{"status":"error","code":2,"message":"filesize(): stat failed for \/PATH\/thumbs\/PATH\/SOMEFILE.jpg in file: \/PATH\/kirby\/vendor\/getkirby\/toolkit\/lib\/f.php on line: 476"}{"status":"error","code":2,"message":"Cannot modify header information - headers already sent by (output started at \/PATH\/kirby\/vendor\/filp\/whoops\/src\/Whoops\/Run.php:398) in file: \/PATH\/site\/plugins\/imagekit\/lib\/complainingthumb.php on line: 152"}
```

the file exists and is 533kb in size. it was created by the following imagekitjob. it seems to fail to verify it?

```php
<?php
return array (
  'imagekit.version' => '1.1.3',
  'source' => 
  array (
    'filename' => 'file-0357.jpg',
    'dir' => NULL,
    'page' => 'PATH',
  ),
  'options' => 
  array (
    'filename' => false,
    'url' => 'http://SOMEURL/thumbs',
    'root' => '/PATH/thumbs',
    'driver' => 'gd',
    'memory' => '128M',
    'quality' => 90,
    'blur' => false,
    'blurpx' => 10,
    'width' => 1920,
    'height' => NULL,
    'upscale' => false,
    'crop' => false,
    'grayscale' => false,
    'overwrite' => false,
    'autoOrient' => false,
    'interlace' => false,
    'bin' => 'convert',
  ),
);
```

3) without debug but with optimisation enabled only one file gets created.
```
{"status":"error","code":0,"message":"An unexpected error occurred! Enable debug mode for more info: https:\/\/getkirby.com\/docs\/cheatsheet\/options\/debug"}{"status":"error","code":0,"message":"An unexpected error occurred! Enable debug mode for more info: https:\/\/getkirby.com\/docs\/cheatsheet\/options\/debug"}
```

is there a way for me to debug the `create` call step by step? adding a php logging call somewhere?

**Comment by bnomei** [comment]
another fact... in the frontend (not the panel) when i have optimisation enabled some images return as error code 500, but they are created on the server. i did check with ftp. maybe the result of the job breaks like the `create`-XHR from the panel – thus returning a 500?

**Comment by bnomei** [comment]
i did call the `http://URL/plugins/imagekit/widget/api/create` directly with debugging enabled. Whoops says it fails at `site/plugins/imagekit/lib/complainingthumb.php` line 152 in `sendErrorResponse()`.

```php
header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0");
```

thats because whoops already did send an error I presume. so when debugging is enabled imagekit can not show an error because whoops breaks its errorhandler. if debugging is disabled imageskit error will not be shown either – which i do not understand.

since i am getting errors from `f::size()` maybe the problem lies here. if optimisation is enabled the filesize is checked here `site/plugins/imagekit/lib/optimizer/jpegtran.php76`:

```
$this->keepSmallestFile($this->thumb->destination->root, $tmpFile);
```

the job creates a tmp file but checking that size fails with an error. maybe a call to [clearstatcache](http://php.net/manual/en/function.clearstatcache.php) is needed since the file was deleted but `file_exists()` returns true since its value is cached?

**Comment by bnomei** [comment]
i think i found it. the optimizer executable was there but owner rightes where not correct. thus the exec failed, and the tmp file never existed causing the `f::size` to fail too.

maybe your optimiser skriptes could check the `return` param of `exec()` like i did for value `126` and display a proper error instead of failing. [read more about it here](http://stackoverflow.com/questions/11511762/exec-php-return-val-is-126).

i also did log the complaining thumb error message: `exif_read_data(SOMEFILE.jpg): Illegal IFD size` which you can [read more about here](http://stackoverflow.com/questions/37352371/php-exif-read-data-illegal-ifd-size). since complaining thumb inherits thumb which uses simpleimage.php from kirby the `get_meta_data()` near line 1119 causes an error. prefixing exif_read_data with `@` does not help like it is described in the stackoverflow posts above. neither will using a try-clause.

my server uses 5.6.28. i will issue an upgrade and report back.

**Comment by bnomei** [comment]
to sum it up...

- fixed my paths of optimisers, which imagekit did not warn me about being wrong, but could.
- fixed permission of optimiser executables. exec failed but imagekit did not care and failed too. solution suggested above using `$return==126`.
- upgraded php from `exif_read_data`-buggy 5.6.2x to 7.x to avoid bug in kirbys `simpleimage` class used by `thumb` extended by imagekits `complaining thumb`.

i leave this issue for @fabianmichael to close.

**Comment by fabianmichael** [comment]
Thanks for your extensive research so far, this is really helpful for me! :-)

Error handlind is always a tricky topic, as one the one hand I don’t want to add too much complexity to ImageKit’s codebase to keep the plugin maintainable. On the other hand, good error-handling can really help users of the plugin as well as clients who only use the panel. I’ll think about a way of how this could all be improved. I already thought about distinguishing between *warnings* (user get’s a message and can continue or abort) and *errors* (use has to restart the thumb generation progress).

I’ll leave this issue open, as I think that error-handling is something that could be done better in general. Maybe this will land in `1.2.0`.

**Comment by wottpal** [comment]
> without optimisation it seems to create 5 – always 5 and then fail.
> [...]
> with debug and with optimisation enabled only one file get created.

I can confirm the behavior that it often only creates 5 and then stops (I have to refresh & restart the process for the next batch). This happens randomly for me either with optimization- and/or debug-enadled or disabled. Really annoying :(
