### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by PaulMorel** [fabianmichael/kirby-imagekit#13]
For even better optimization, I think it would be great to have WebP support (like EWWW Image Optimizer does) and serve it only to the browsers that support it.

At the time of writing, only Chrome and Opera supports the file type.

**Comment by fabianmichael** [comment]
We had a discussion about that in the Kirby forum a while ago. For now, this would IMHO require a completely different approach of how Kirby handles thumbnail creation, so while I’m somewhat optimistic that I’ll include that in a future version, this is not something that will happen within the nexts weeks or months. So sorry for now, but I’ll keep this issue open and tagged as idea.

https://forum.getkirby.com/t/imagekit-an-asynchronous-thumbs-api/4601/32?u=fabianmichael

**Comment by fabianmichael** [comment]
WebP-support will be reconsidered for the Kirby 3.0-compatible version.
