### ISSUE TITLE
Mac mozjpeg is in brew

### ISSUE THREAD

**Issue by shoesforindustry** [fabianmichael/kirby-imagekit#17]
You can of course get 'mozjpeg' from brew on a Mac ;-)
`brew install  #mozjpeg`

if you don't have hombrew:
https://brew.sh/

Also wanted to say thank you for this plugin, it is splendid, still testing but will be buying some licenses soon.

**Comment by fabianmichael** [comment]
Thanks for the hint, will add to docs soon.
