### ISSUE TITLE
Feature-Request: Imageset + Focus

### ISSUE THREAD

**Issue by wottpal** [fabianmichael/kirby-imagekit#21]
Would be so cool to use the focus-selector in the panel by @flokosiol and get thumbs asynchronously generated by ImageKit.

Dennis

**Comment by fabianmichael** [comment]
You mean defining a focus point, that is respected by ImageSet?

**Comment by wottpal** [comment]
Yep

**Comment by flokosiol** [comment]
Let me know if there's anything to adjust for me on Focus side. I would happily support your plugin. 😉

**Comment by rcvd** [comment]
Any news on this?

**Comment by fabianmichael** [comment]
Sorry, that I’ve been so quiet. This would be a very nice feature, of course! ImageSet will need a complete overhaul for Kirby 3 anyway, so I think that this would really be a nice addition. If it’s not too much of a hassle to support the Kirby 2 version as well, I can add this feature to the "old" version as well.
