### ISSUE TITLE
Widget conflict

### ISSUE THREAD

**Issue by guidoferreyra** [fabianmichael/kirby-imagekit#23]
Hi I’m getting the following error the I try to generate the thumbs via the widget. 

`Undefined index: newCustomer in file: .../site/plugins/shopkit/shopkit.php on line: 940`

Any idea? Thanks in advance.

**Comment by fabianmichael** [comment]
Sorry, I’m not a user of Shopkit and thus don’t know what causes the conflict …

But please tell me a bit more about your setup: I just had a brief look at the git repo of Shopkit and it does not access any array on line 940. Which version of Shopkit and Kirby are you using? Is your error part of an AJAX request made by ImageKit?

**Comment by fabianmichael** [comment]
Closed, as no further details were submitted by reporter for several months.
