### ISSUE TITLE
How to trigger thumbnail-generation with cronjob on VPS?

### ISSUE THREAD

**Issue by wottpal** [fabianmichael/kirby-imagekit#28]
Hey Fabian,
I imagine running the "Create" task every night automatically with a cronjob. Do you have any ideas how to do that? 

Dennis

**Comment by fabianmichael** [comment]
Hi Dennis,

this is not possible (yet), but it’s a great idea. :-) I will try to implement it for the Kirby 3.0-compatible version, but cannot promise when it will be ready. But I've created an issue for that: #29

Best,
Fabian
