### ISSUE TITLE
Kirby 3

### ISSUE THREAD

**Issue by mmeinesz** [fabianmichael/kirby-imagekit#32]
are you planing to update to Kirby 3?
We are using a 2.x version of Kirby right now, but I do plan to update. Your imagekit would really speed our pages up, so it would be nice to integrate it together with the update ;-)

**Comment by fabianmichael** [comment]
Sorry, there are not fixed plans yet. As an asynchronuous thumbnail engine is now part of the Kirby core, it does not really make sense to port the whole plugin to Kirby 3 any more. I am currently thinking about releasing the optimization part as successor to ImageKit, but some important APIs for Kirby 3 are still missing.

**Comment by fabianmichael** [comment]
@mmeinesz I had to end all development on ImageKit, please see https://forum.getkirby.com/t/the-end-of-imagekit-and-imageset/15824 for a more detailed explanation.
