### ISSUE TITLE
Panel Widget Doesn't Show Image Counts

### ISSUE THREAD

**Issue by azharc** [fabianmichael/kirby-imagekit#5]
Testing out ImageKit, which is an amazing plugin!

The panel widget is showing '...' for both items though, even though the plugin seems to be working properly. 

There is nothing in the error logs (or console). 

Kirby & Panel 2.3.2, PHP 7, Apache. 

Is there anything else I can do to help diagnose this issue? Enabling imagekit.debug doesn't seem to provide any useful information. 

![screen shot 2016-11-25 at 8 42 48 pm](https://cloud.githubusercontent.com/assets/2773389/20637252/cda64c18-b34f-11e6-95fb-c4a35a4816c4.png)

Thank you Fabian!

**Comment by fabianmichael** [comment]
Hey @azharc,

`imagekit.debug` is currently meant for development purposes of the plugin and it’s main function is to avoid the deletion of job files in your thumbs directory.

To chase your issue, the first step would be to open the web development tools and watch for an XHR (Ajax) request to `plugins/imagekit/widget/api/status`. Please check the response of that request and tell me, what the server responds. Which browser are us using?

Thanks for your help.

Cheers
Fabian

**Comment by azharc** [comment]
Hi Fabian, 

I found the issue. Seems like the JS file wasn't being loaded at all. 

All I had to do was change line 45 in imagekit.html.php to:
` echo f::read(__DIR__ . '/assets/js/dist/widget.min.js');`

Previously it was referencing 'widget.js' which doesn't exist.

**Comment by fabianmichael** [comment]
Thanks for your help, just pushed a commit (b8da0cab827138c5c1f4e95fc14f5844b45b0694) that fixes this.

Have a nice sunday :-)
