### ISSUE TITLE
Unknown page is coming up during thumb creation process

### ISSUE THREAD

**Issue by jakobploens** [fabianmichael/kirby-imagekit#6]
I've tested the imagekit plugin a couple of times in several projects, and it always worked very well (though it never was used at production pages due to other reasons). Now I'm again trying to implement it to a image-heavy site where the client asked exactly for such a feature. But this time it drives me crazy – when I'm using the create-funtion within the panel widget, it always adds another site during the image-search process – and I have absolute no idea why. No errors are shown, the process just stops at the last page:

- Pages are searched, 249 found
- When searching for thumbnails/images, at page ~220 or something, another page is added – we have now 250
- Widget stops at 249/250

I'm using the default setting for imagekit, and have several plugins installed, and also tested all the plugins within a clean starterkit installation, where it always works perfectly. Do you have any idea or hint where I can have a deeper look? Would be awesome!

Edit: disabling the discover mode helps with creating the thumbnails. However, I'd really like the client to be able to use also the discover mode…

**Comment by jakobploens** [comment]
Okay, I found the issue – there are links with the "rel" attribute for next/prev pages, which link to `javascript:;`. Of course this XHR request will return nothing… but maybe that's a thing the plugin should handle…?

**Comment by fabianmichael** [comment]
Although you already closed this, it seems to make sense to me to validate the links before sending a request to them. I updated the plugin to do this.

BTW, ff your markup does not work without `javascript:;` or whatsoever, you can now also add the corresponding links for prev/next pages for search engines and ImageKit to the <head> of your page:

```html
<link rel="next" href="/blog/page:2">
```
